version: '3.8'

services:
  kakujoe-seri-dx-db:
    container_name: kakujoe-seri-dx-db
    image: mysql:5.7.33 # This version should be same with AWS RDS MySQL version
    platform: linux/x86_64 # For M1 Mac. MySQL can't work on ARM64.
    command: |
      --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - kakujoe-seri-dx-db-data:/var/lib/mysql:delegated
    ports:
      - 3306:3306  # host:container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=database

volumes:
  kakujoe-seri-dx-db-data:
    driver: local